name: prisma_env
description: This package is used to read the environment configuration required by Prisma set via Dart --define.
version: 0.0.0
homepage: https://prisma.pub
repository: https://github.com/odroe/prisma-dart/tree/main/packages/prisma_env

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
