name: simple_example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  faker: ^2.0.0
  orm: any

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  lints: ^2.0.0

dependency_overrides:
  orm:
    path: ../../
