name: orm_flutter_ffi
description: Prisma C-ABI query engine FFI bindings.

resolution: workspace
version: 0.0.1

environment:
  sdk: ^3.5.0

dependencies:
  orm_flutter_ios: ^0.0.1

dev_dependencies:
  lints: ^5.0.0
  ffigen: ^15.0.0

ffigen:
  name: QueryEngineBindings
  description: |
    Bindings for `query_engine_bridge.h`.

    Regenerate bindings with `dart run ffigen`.
  output: lib/src/_generate_bindings.dart
  language: c
  headers:
    entry-points:
      - ../query_engine_bridge/headers/bridge.h
    include-directives:
      - ../query_engine_bridge/**
  comments:
    style: any
    length: full
  silence-enum-warning: true
  functions:
    exclude:
      - prisma_.*
  globals:
    exclude:
      - PRISMA_.*
