name: prisma_engines_download
description: Prisma ORM engines download library.
version: 1.0.0
repository: https://github.com/odroe/prismaorm

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  archive: ^3.3.1
  http: ^0.13.4
  path: ^1.8.2
  prisma_common: ^1.0.0
  prisma_engines_platform: ^1.0.0
  prisma_engines_version: ^1.0.0

dependency_overrides:
  prisma_common:
    path: ../prisma_common
  prisma_engines_platform:
    path: ../prisma_engines_platform
  prisma_engines_version:
    path: ../prisma_engines_version

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
