name: prisma_dart_example
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  json_annotation: ^4.8.1
  orm:
    path: ../

dev_dependencies:
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
