name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  orm: any

dev_dependencies:
  lints: ^2.0.0

dependency_overrides:
  orm:
    path: ..
