name: prisma_dart_client_example
description: Prisma Dart Client Example
publish_to: 'none'
version: 1.0.0
repository: https://github.com/medz/prisma-dart
homepage: https://github.com/medz/prisma-dart/tree/master/example
environment:
  sdk: ^3.2.0
dependencies:
  orm:
    path: ../
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.8
