# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/zh/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-the-dependabotyml-file

version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: 'ci(deps)'

  # `orm` package
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: 'fix(deps)'

  # # rust crates
  # - package-ecosystem: cargo
  #   directory: /
  #   schedule:
  #     interval: daily
  #   commit-message:
  #     prefix: 'fix(deps)'

  # npm
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: 'chore(deps)'
