version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: 'ci(deps)'

  # Workspace
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: 'chore(deps)'

  # `package:orm` Prisma Dart client
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: 'build(deps)'
