# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/cn/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-the-dependabotyml-file

version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  # Documentation
  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: daily
    labels:
      - docs

  # `orm` package
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: daily

  # Simple example
  - package-ecosystem: pub
    directory: /example/simple
    schedule:
      interval: daily
    labels:
      - "example"

  # RESTful example
  - package-ecosystem: pub
    directory: /example/rest_api
    schedule:
      interval: daily
    labels:
      - "example"

  # Flutter example
  - package-ecosystem: pub
    directory: /example/flutter_data_proxy
    schedule:
      interval: daily
    labels:
      - "example"

  # Prisma get platform
  - package-ecosystem: pub
    directory: /packages/prisma_get_platform
    schedule:
      interval: daily
