name: orm
description: ◭ Next-generation ORM for Dart Navtive & Flutter | PostgreSQL, MySQL, MariaDB, SQL Server, SQLite, MongoDB and CockroachDB.
version: 2.0.0-dev
repository: https://github.com/odroe/orm.dart

environment:
  sdk: '>=2.17.6 <3.0.0'

executables:
  prisma: orm
  prisma-client-dart: prisma_client_generator

dependencies:
  archive: ^3.3.1
  args: ^2.3.1
  http: ^0.13.5
  json_annotation: ^4.6.0
  path: ^1.8.2
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  lints: ^2.0.0
