name: rest_api
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  lints: ^2.0.0
  
dependencies:
  orm: ^3.0.1-beta+0
  spry: ^0.4.0
  spry_interceptor: ^0.3.0
  spry_json: ^0.3.0
  spry_router: ^0.4.1
