name: prisma_query_engine
description: ◭ Prisma ORM engine wrapper.
version: 1.0.0
repository: https://github.com/odroe/orm.dart

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
