name: prisma_query_engine
description: ◭ Prisma ORM engine wrapper.
version: 1.0.0
repository: https://github.com/odroe/orm.dart

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  http: ^0.13.5
  path: ^1.8.0
  prisma_shared: ^1.0.0

dev_dependencies:
  ffigen: ^6.0.1
  lints: ^2.0.0
  test: ^1.16.0

dependency_overrides:
  prisma_shared:
    path: ../prisma_shared
