[package]
name = "engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.151"
prisma-fmt = { git = "https://github.com/prisma/prisma-engines", version = "0.1.0" }
