[package]
name = "engine_ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
query-engine-wasm = { git = "https://github.com/medz/prisma-engines", branch = "prisma-dart", version = "0.1.0" }
serde_json = "1.0.108"
