[package]
name = "prisma-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
lsp-types = "0.94.1"
prisma-fmt = { git = "https://github.com/prisma/prisma-engines", tag = "5.6.0", version = "0.1.0" }
serde_json = "1.0.108"
