name: orm
description: Next-generation ORM for Dart Navtive & Flutter | PostgreSQL, MySQL, MariaDB, SQL Server, SQLite, MongoDB and CockroachDB.
version: 1.0.5
repository: https://github.com/odroe/orm.dart

environment:
  sdk: '>=2.17.6 <3.0.0'

executables:
  prisma: orm
  orm: orm

dev_dependencies:
  lints: ^2.0.0
  prisma_cli: any

dependency_overrides:
  prisma_cli:
    path: ../prisma_cli
