name: orm
description: Next-generation ORM for Dart Navtive & Flutter | PostgreSQL, MySQL, MariaDB, SQL Server, SQLite, MongoDB and CockroachDB.
version: 1.0.3
repository: https://github.com/odroe/orm.dart

environment:
  sdk: '>=2.17.6 <3.0.0'

executables:
  prisma: orm

dependencies:
  archive: ^3.3.1
  args: ^2.3.1
  cli_util: ^0.3.5
  http: ^0.13.4
  io: ^1.0.3
  path: ^1.8.2
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
