name: orm
description: ◭ Next-generation ORM for Dart Navtive & Flutter | PostgreSQL, MySQL, MariaDB, SQL Server, SQLite, MongoDB and CockroachDB.
version: 1.0.5
repository: https://github.com/odroe/orm.dart

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  prisma_query_engine: ^1.0.0
  
dev_dependencies:
  lints: ^2.0.0
  prisma_cli: ^1.0.0

dependency_overrides:
  prisma_cli:
    path: ../prisma_cli
  prisma_query_engine:
    path: ../prisma_query_engine
