name: orm
description: Dart ORM library.
version: 1.0.0
repository: https://github.com/odroe/prismaorm

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  path: ^1.8.2
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
