name: readme_example
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  orm: ^2.1.3

dev_dependencies:
  build_runner: ^2.2.1
  json_serializable: ^6.3.2
  lints: ^2.0.0

dependency_overrides:
  orm:
    path: ../../
