name: orm_flutter
description: "The engine of Prisma ORM for Flutter, Library for binding Prisma's C-Abi engine with Flutter."
homepage: https://prisma.pub/getting-started/flutter.html
repository: https://github.com/medz/prisma-dart

resolution: workspace
version: 0.3.1

funding:
  - https://github.com/sponsors/medz
  - https://opencollective.com/openodroe

environment:
  sdk: ^3.5.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.3
  orm: ^5.2.0
  path: ^1.9.0
  path_provider: ^2.1.4
  orm_flutter_ios: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        default_package: orm_flutter_ios
