name: prisma_cli
description: ◭ Prisma is a modern DB toolkit to query, migrate and model your database
version: 1.0.5
repository: https://github.com/odroe/orm.dart

environment:
  sdk: '>=2.17.6 <3.0.0'

executables:
  prisma-cli: prisma_cli
  prisma-dart-client: prisma_client_generator

dependencies:
  archive: ^3.3.1
  args: ^2.3.1
  http: ^0.13.4
  json_annotation: ^4.6.0
  build_runner: ^2.2.0
  path: any
  yaml: any

dev_dependencies:
  json_serializable: ^6.3.1
  lints: ^2.0.0
  orm: ^1.0.4
  test: ^1.16.0

dependency_overrides:
  orm:
    path: ../orm
