name: prisma_dmmf
description: ◭ Prisma ORM schema DMMF document parser.(See https://github.com/prisma/prisma/blob/main/packages/generator-helper/src/dmmf.ts)
version: 1.0.0
repository: https://github.com/odroe/orm.dart

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  lints: ^2.0.0
