name: analyze
on:
  push:
    paths-ignore:
      - "docs/**"
  pull_request:
      paths-ignore:
        - "docs/**"
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.4
      - name: Install dependencies
        run: dart pub get
      - name: Analyze bin
        run: dart analyze bin
      - name: Analyze lib
        run: dart analyze lib
