name: prisma_engine_core
description: The package is a Prisma query engine interface. It is used by the Prisma Client to communicate with the Prisma query engine.
version: 0.0.0
homepage: https://prisma.pub
repository: https://github.com/odroe/prisma-dart/tree/main/packages/prisma_engine_core

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  crypto: ^3.0.2
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  http: ^0.13.5
  prisma_event: ^0.0.0
  retry: ^3.1.0
