name: example
description: ◭ Prisma is a modern DB toolkit to query, migrate and model your database
version: 1.0.5
repository: https://github.com/odroe/orm.dart
publish_to: none

dependencies:
  json_annotation: ^4.6.0
  build_runner: ^2.2.0
  orm: 
    path: ../

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  json_serializable: ^6.3.1
  lints: ^2.0.0

