name: shelf_example
description: Prisma ORM + Shelf example.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  args: ^2.0.0
  json_annotation: ^4.7.0
  orm:
    path: ../../
  shelf: ^1.1.0
  shelf_router: ^1.0.0

dev_dependencies:
  build_runner: ^2.2.1
  http: ^0.13.0
  json_serializable: ^6.4.0
  lints: ^2.0.0
