name: prisma_shared
description: ◭ Prisma is a modern DB toolkit to query, migrate and model your database
version: 1.0.5
repository: https://github.com/odroe/orm.dart

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  json_annotation: ^4.6.0
  yaml: any

dev_dependencies:
  json_serializable: ^6.3.1
  lints: ^2.0.0
  orm: ^1.0.4


