[package]
name = "engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

doc = false
crate-type = ["cdylib", "staticlib"]

[dependencies]

query-engine-common = {git = "https://github.com/prisma/prisma-engines"}
