name: prisma_engines_version
description: Prisma ORM engines version library.
version: 1.0.0
repository: https://github.com/odroe/prismaorm

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
