name: orm_flutter_ios
description: "A new Flutter FFI plugin project."
version: 0.0.1

environment:
  sdk: ^3.5.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
