name: orm_flutter_ios
description: "Prisma Query Engine implementation for iOS platform (FFI)"
homepage: https://prisma.pub

resolution: workspace
version: 0.0.1

environment:
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
