name: sqlite
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.2.1
  json_serializable: ^6.4.0
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  orm:
    path: ../..
