[package]
name = "prisma_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
engine = { version = "0.1.0", path = "../engine" }
futures = "0.3.29"
libc = "0.2.151"
serde_json = "1.0.108"
tokio = "1.35.0"
