[package]
name = "prisma_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opentelemetry = "0.17"
prisma-fmt = { git = "https://github.com/prisma/prisma-engines" }
psl = { git = "https://github.com/prisma/prisma-engines", version = "0.1.0" }
quaint = { git = "https://github.com/prisma/prisma-engines", version = "0.2.0-alpha.13" }
query-core = { git = "https://github.com/prisma/prisma-engines" }
query-engine-common = { git = "https://github.com/prisma/prisma-engines" }
request-handlers = { git = "https://github.com/prisma/prisma-engines", default-features = false, features = ["sql"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["float_roundtrip", "preserve_order"] }
tokio = { version = "1.35.1", features = ["macros", "sync", "io-util", "time"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-opentelemetry = "0.17.3"
tracing-subscriber = "0.3"

[build-dependencies]
cbindgen = "0.26.0"
