[package]
name = "prisma_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prisma-fmt = { git = "https://github.com/prisma/prisma-engines" }

[build-dependencies]
cbindgen = "0.26.0"
