name: test
on:
  - push
  - pull_request
jobs:
  build:
    matrix:
      os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: "npm"
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run:
          if: matrix.os == 'windows-latest'
          name: Run Prisma info
          run: dart test test\generator\prisma_info_test.dart
      - run:
          if: matrix.os == 'ubuntu-latest'
          name: Run tests
          run: dart test
